name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get PR diff
      id: diff
      run: |
        PR_DIFF=$(gh pr diff ${{ github.event.pull_request.number }} --patch)
        echo "$PR_DIFF" > pr_diff.patch
        echo "::set-output name=diff::$(echo $PR_DIFF)"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Get PR description
      id: description
      run: echo "::set-output name=description::${{ github.event.pull_request.body }}"

    - name: Call ChatGPT API
      id: review
      run: |
        DIFF=$(cat pr_diff.patch)
        DESCRIPTION=${{ steps.description.outputs.description }}
        echo "diff $DIFF"
        echo "description $DESCRIPTION"
        RESPONSE=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "model": "gpt-4o",
                "messages": [
                  {
                    "role": "system",
                    "content": "You are a helpful assistant."
                  },
                  {
                    "role": "user",
                    "content": "以下のプルリクエストをレビューしてください:\n\nDescription: ' + $DESCRIPTION + '\n\nDiff: '+ $DIFF + '"
                  }
                ]
              }'
        )
        echo "response $RESPONSE"
        echo "::set-output name=response::$(echo $RESPONSE | jq -r '.choices[0].message.content')"

    - name: Post review comment
      run: |
        REVIEW_COMMENT=${{ steps.review.outputs.response }}
        gh pr comment ${{ github.event.pull_request.number }} --body "$REVIEW_COMMENT"
      env:
        GH_TOKEN: ${{ github.token }}
